[package]
name = "gym-rs"
version = "0.2.1"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "OpenAI's Gym written in pure Rust"
repository = "https://github.com/MathisWellmann/gym-rs"
readme = "README.md"
keywords = [
    "rl",
    "ai",
    "ml",
    "physical",
    "environment",
    "benchmark",
]
categories = [
    "simulation",
    "science",
    "algorithms",
]
exclude = [
    "img/"
]

[dependencies]
rand = "^0.7.3"
rand_pcg = "0.2.1"
log = "0.4.11"
num = "0.3.0"
find_folder = "0.3.0"
failure = "0.1.8"
plotters = "0.3.0"
