[package]
name = "gym-rs"
version = "0.1.1"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.3"
rand_pcg = "0.2.1"
log = "0.4.11"
num = "0.3.0"
find_folder = "0.3.0"
piston_window = "0.116.0"

cge = { git = "https://github.com/pengowen123/cge", optional = true }

[[example]]
name = "cart_pole_random"

[[example]]
name = "cart_pole_random_render"

[[example]]
name = "cart_pole_solved_render"
required-features = ["cge"]